name: Build Kernel AOSP Pipa

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip ccache gcc g++ lld libncurses-dev bc bison flex libssl-dev curl

      - name: Download Clang r547379 from AOSP
        run: |
          mkdir -p $HOME/tc
          curl -L -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz
          tar -C $HOME/tc -xzf clang.tar.gz

      - name: Set permission to build.sh
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh

      - name: Upload kernel zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-flashable-zip
          path: |
            *.zip
