name: Build Kernel AOSP Pipa

on:
  workflow_dispatch:
  push:
    branches:
      - main  # ganti jika perlu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip ccache gcc g++ clang lld libncurses-dev bc bison flex libssl-dev

      - name: Set permission to build.sh
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh

      - name: Upload kernel zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-flashable-zip
          path: |
            *.zip
            
